In [78]:
import numpy as np

https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

Question - what is an array?

ARR= a grid of values, indexed by integers, all values being the same dtype \
Arrays can be multidimensional\
from 0 dimensional to N dimensional\
0 dimensional = 'scalar' 


In [79]:
#why is numpy needed 
lst=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [80]:
#I want to add 2 to each value in my list 
# lst+2

In [81]:
#define the same list as an array 
arr=np.array([1,2,3,4,5])

#could also have used my_array = np.array(my_list)

In [82]:
#now lets add 2 to each value in the list 
arr+2

array([3, 4, 5, 6, 7])

### 0 and 1 dimension arrays (and some fun friday maths)

In [83]:
#example of a 0 d array 
a=np.array(1)
a.ndim

0

In [84]:
#example of a 1 d array 
b=np.array([1,2,3,4,5])
b.ndim
#try filling the variable b with a different/longer/more diverse array
#just stick to the format v=np.array([#,#,...])

1

In [85]:
#use shape to check the shape of the array 
a.shape

()

In [86]:
#use shape to check the shape of the array 
b.shape

(5,)

In [87]:
#Access the second element from the array
b[1]

2

In [88]:
#try some basic maths operators with your array:
np.sum(b)
#eg median,mean,diff,max,min,prod,cumsum,cumprod

15

https://numpy.org/doc/stable/reference/routines.math.html

#### Talking of maths ... 

cast your minds back to when you were in school, remember this?

In [89]:
# conda install -c anaconda ipython

In [90]:
# from IPython.display import Image
# Image("pythag.png")

In [91]:
#lets revisit those nightmares and do some Pythag! 
# define your right angled triangle:
base= 20
perp= 30
#use np to calculate the length of the hypoteneuse
hyp=np.hypot(base, perp)
hyp 

36.05551275463989

In [92]:
#check the above using the old fashioned method hint: import math for sqrt
import math
hyp=math.sqrt((base*base)+(perp*perp))
hyp

36.05551275463989

In [93]:
#To pick up Simons question on float64... np can explain it visually 

p=np.array((0.12345678976543,1,2,3),dtype=np.float16) #1 d array
print(p[0])

0.1235


In [94]:
q=np.array((0.12345678976543,1,2,3),dtype=np.float32)
print(q[0])

0.12345679


In [95]:
r=np.array((0.12345678976543,1,2,3),dtype=np.float64)
print(r[0])

0.12345678976543


## Multi dimensional np arrays 

In [96]:
#example of a 2d array
c=np.array([[2,2,2,2],[8,7,6,5],[3,3,3,3]])
c.ndim
#try filling the variable c with a different/longer/more diverse array
#just stick to the format v=np.array([[#],[#],...])

2

In [97]:
# Image('2darray.png')

In [98]:
#view the variable c as a matrix of rows and columns
c

array([[2, 2, 2, 2],
       [8, 7, 6, 5],
       [3, 3, 3, 3]])

In [99]:
#use shape to check the shape of the array c # (rows, columns)
c.shape

(3, 4)

In [100]:
#Access the THIRD element from the second row of the array using v[][] # 
c[1][2]

#hint: row comes first

6

In [101]:
# of course a pandas df is also a 2d np array
# import pandas as pd 
# df=pd.read_csv('checkpoint2.csv')#read any csv file here 
# df.ndim


In [102]:
#check the shape - which is first in (n,n), rows or columns? why?


In [103]:
#as with pandas we can apply maths operators to the 2d array c

c.sum(axis=1)

#try defining the axis along which you wish to sum in ()
# experiment with the other maths operators as for the 1d array

array([ 8, 26, 12])

In [114]:
#whats the min and max of each column of the array?
#print(c.min(axis=0))
c.max(axis=0)

#print(c.min(axis=1))
#print(c.max(axis=1))

array([8, 7, 6, 5])

In [119]:
#whats the difference between the variance in each row of the array 
# as compared to the overall array variance? 

diff=c.var()-c.var(axis=1)
diff

array([4.13888889, 2.88888889, 4.13888889])

In [106]:
#example of a 3d array 
d=np.array([[[1,2,3], [4,4,4], [1,2,1], [3,2,2]], [[5,6,7], [8,7,8], [9,9,9], [5,5,6]]])
d.ndim
# a 3d array can be imagined as n x 2 d arrays 

3

In [120]:
#view the variable d as a matrix of rows and columns
d

array([[[1, 2, 3],
        [4, 4, 4],
        [1, 2, 1],
        [3, 2, 2]],

       [[5, 6, 7],
        [8, 7, 8],
        [9, 9, 9],
        [5, 5, 6]]])

In [121]:
#use shape to check the shape of the array 
d.shape

(2, 4, 3)

In [122]:
# Image("3darray.png")

It can be hard to envisage a 3d array, so think of it like a cube

this might make for interesting reading on cubes: \
https://www.holistics.io/blog/the-rise-and-fall-of-the-olap-cube/

In [123]:
#another way to make a 3d array - using random
e = np.random.rand(3,3,3)
e
#random.rand - create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

array([[[0.37868255, 0.48326011, 0.35420346],
        [0.80746458, 0.38001403, 0.22667496],
        [0.72932114, 0.0132719 , 0.42226722]],

       [[0.87210918, 0.95487178, 0.97825063],
        [0.29610939, 0.64037413, 0.66817399],
        [0.0468831 , 0.78228779, 0.6175822 ]],

       [[0.70477272, 0.35043669, 0.92534943],
        [0.38847065, 0.47502705, 0.14560871],
        [0.37074853, 0.29150967, 0.88216581]]])

In [125]:
#confirm the no of dimensions of e 
e.ndim

3

In [128]:
#create a 3d array of only zeros, hint: ask google 
zero = np.zeros((3, 3, 3)) # np.zeros(dimension)
zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Class experiment

* lets define a 2d array together by capturing some data from eachother
* students will be organised into 4 breakout rooms of 6 
* Each group picks a data question from this [list](https://docs.google.com/spreadsheets/d/10Jj_w8Klj9u7NoPxqq5CqSbj0MPTDfKMHsOfkJ6nUM0/edit?usp=sharing) and collects data points from each student in the group to form a 1d array
* each group will provide a 6 digit 1d array via the chat
* everyone builds the same class 2d array
* we will know the groups/members but not which question was chosen
* through the process of analysing the 2d array we put together, can we guess which questions were chosen by each group?



In [130]:
# 'How many languages do you speak?'
lst=[6,3,4,3,3]
arr=np.array(lst)

In [131]:
arr

array([6, 3, 4, 3, 3])

In [129]:
classmates = np.array([[20,2,2,7,2,6],[6,3,4,3,3,3],[4,3,4,3,4],[29,1,2,7,5,8]